;;; -*- coding: utf-8; mode: lisp-data -*-
(("/Users/akdeniz/dev/federal_ateriel/components/preview-3d.tsx"
  . 3091)
 ("/Users/akdeniz/dev/lazyfocus/src/main.rs" . 741)
 ("/Users/akdeniz/dev/lazyfocus/src/todo/mod.rs" . 15)
 ("/Users/akdeniz/dev/lazyfocus/src/ui.rs" . 933)
 ("/Users/akdeniz/dev/pokemon-dimensions/src/pokemon/Pokemon.ts" . 653)
 ("/Users/akdeniz/dev/federal_ateriel/app/customize/PreviewDesignStepper.tsx"
  . 3643)
 ("/Users/akdeniz/.emacs.d/"
  (dired-filename . "/Users/akdeniz/.emacs.d/modules"))
 ("/Users/akdeniz/.emacs.d/modules/"
  (dired-filename . "/Users/akdeniz/.emacs.d/modules/auto-complete.el"))
 ("/Users/akdeniz/.emacs.d/modules/auto-complete.el" . 662)
 ("/Users/akdeniz/dev/federal_ateriel/app/customize/ChooseProductStepper.tsx"
  . 33)
 ("/Users/akdeniz/dev/federal_ateriel/lib/utils.ts" . 172)
 ("/Users/akdeniz/" (dired-filename . "/Users/akdeniz/.emacs.d"))
 ("/Users/akdeniz/dev/federal_ateriel/app/about/page.tsx" . 278)
 ("/Users/akdeniz/.emacs.d/modules/lsp.el" . 66)
 ("/Users/akdeniz/dev/federal_test/main.js" . 1307)
 ("/Users/akdeniz/dev/federal_ateriel/app/customize/page.tsx" . 5669)
 ("/Users/akdeniz/dev/federal_ateriel/app/page.tsx" . 400)
 ("/Users/akdeniz/.emacs.d/modules/modeline.el" . 86)
 ("/Users/akdeniz/.emacs.d/modules/terminal.el" . 336)
 ("/Users/akdeniz/.emacs.d/modules/git.el" . 18)
 ("/Users/akdeniz/.emacs.d/modules/general.el" . 1528)
 ("/Users/akdeniz/.emacs.d/modules/options.el" . 1765)
 ("/Users/akdeniz/dev/federal_ateriel/components/"
  (dired-filename
   . "/Users/akdeniz/dev/federal_ateriel/components/client-logos.tsx"))
 ("/Users/akdeniz/dev/federal_ateriel/hooks/"
  (dired-filename
   . "/Users/akdeniz/dev/federal_ateriel/hooks/use-mobile.tsx"))
 ("/Users/akdeniz/dev/federal_ateriel/lib/"
  (dired-filename . "/Users/akdeniz/dev/federal_ateriel/lib/utils.ts"))
 ("/Users/akdeniz/dev/federal_ateriel/"
  (dired-filename . "/Users/akdeniz/dev/federal_ateriel/app"))
 ("/Users/akdeniz/dev/federal_ateriel/app/customize/UploadLogoStepper.tsx"
  . 4093)
 ("/Users/akdeniz/dev/federal_ateriel/app/customize/"
  (dired-filename
   . "/Users/akdeniz/dev/federal_ateriel/app/customize/page.tsx"))
 ("/Users/akdeniz/dev/federal_ateriel/components/client-logos.tsx"
  . 68)
 ("/Users/akdeniz/dev/federal_ateriel/app/"
  (dired-filename
   . "/Users/akdeniz/dev/federal_ateriel/app/layout.tsx"))
 ("/Users/akdeniz/dev/federal_ateriel/app/layout.tsx" . 363)
 ("/Users/akdeniz/dev/lyvia/src/app/layout.tsx" . 591)
 ("/Users/akdeniz/dev/federal_test/index.html" . 380)
 ("/Users/akdeniz/.emacs.d/modules/perspective.el" . 125)
 ("/Users/akdeniz/dev/store-app/lib/utils.ts" . 103)
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/page.tsx"
  . 2426)
 ("/Users/akdeniz/.emacs.d/straight/"
  (dired-filename . "/Users/akdeniz/.emacs.d/straight/repos"))
 ("/Users/akdeniz/.emacs.d/modules/evil.el" . 1276)
 ("/Users/akdeniz/.emacs.d/modules/project.el" . 461)
 ("/Users/akdeniz/.emacs.d/modules/file.el" . 1140)
 ("/Users/akdeniz/dev/wukong/parser/parser.go" . 10447)
 ("/Users/akdeniz/dev/wukong/"
  (dired-filename . "/Users/akdeniz/dev/wukong/lexer"))
 ("/Users/akdeniz/dev/wukong/lexer/"
  (dired-filename . "/Users/akdeniz/dev/wukong/lexer/lexer.go"))
 ("/Users/akdeniz/dev/wukong/lexer/lexer.go" . 1112)
 ("/Users/akdeniz/.emacs.d/modules/copilot.el" . 281)
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/app/dashboard/reports"))
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/reports/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/app/dashboard/reports/all"))
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/reports/all/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/app/dashboard/reports/all/page.tsx"))
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/reports/all/page.tsx"
  . 1336)
 ("/Users/akdeniz/.emacs.d/modules/pdf.el" . 46)
 ("/Users/akdeniz/dev/kairo/src/main.rs" . 152)
 ("/Users/akdeniz/.emacs.d/modules/ui.el" . 708)
 ("/Users/akdeniz/.emacs.d/init.el" . 798)
 ("/Users/akdeniz/.emacs.d/.projectile" . 46)
 ("/Applications/Xournal++.app/Contents/Resources/plugins/Pen-GUI-n/"
  (dired-filename
   . "/Applications/Xournal++.app/Contents/Resources/plugins/Pen-GUI-n/main.lua"))
 ("/Applications/Xournal++.app/Contents/Resources/plugins/Pen-GUI-n/main.lua"
  . 1096)
 ("/" (dired-filename . "/Applications"))
 ("/Applications/" (dired-filename . "/Applications/Xournal++.app"))
 ("/Applications/Xournal++.app/"
  (dired-filename . "/Applications/Xournal++.app/Contents"))
 ("/Applications/Xournal++.app/Contents/"
  (dired-filename . "/Applications/Xournal++.app/Contents/Resources"))
 ("/Applications/Xournal++.app/Contents/Resources/"
  (dired-filename
   . "/Applications/Xournal++.app/Contents/Resources/plugins"))
 ("/Applications/Xournal++.app/Contents/Resources/plugins/"
  (dired-filename
   . "/Applications/Xournal++.app/Contents/Resources/plugins/Pen-GUI-n"))
 ("/Users/" (dired-filename . "/Users/akdeniz"))
 ("/Users/akdeniz/dev/kairo/src/app.rs" . 1364)
 ("/Users/akdeniz/dev/kairo/src/"
  (dired-filename . "/Users/akdeniz/dev/kairo/src/canvas.rs"))
 ("/Users/akdeniz/dev/kairo/"
  (dired-filename . "/Users/akdeniz/dev/kairo/Cargo.toml"))
 ("/Users/akdeniz/dev/kairo/Cargo.toml" . 92)
 ("/Users/akdeniz/dev/kairo/src/canvas.rs" . 634)
 ("/Users/akdeniz/.emacs.d/modules/auto-pair.el" . 1152)
 ("/Users/akdeniz/.emacs.d/modules/code-runner.el" . 764)
 ("/Users/akdeniz/.emacs.d/modules/popper.el" . 297)
 ("/Users/akdeniz/dev/kairo/doc.org" . 471)
 ("/Users/akdeniz/dev/rustlings/exercises/06_move_semantics/move_semantics5.rs"
  . 451)
 ("/Users/akdeniz/dev/rustlings/exercises/06_move_semantics/move_semantics4.rs"
  . 404)
 ("/Users/akdeniz/dev/rustlings/exercises/06_move_semantics/move_semantics3.rs"
  . 138)
 ("/Users/akdeniz/dev/rustlings/exercises/06_move_semantics/move_semantics2.rs"
  . 441)
 ("/Users/akdeniz/dev/rustlings/exercises/06_move_semantics/move_semantics1.rs"
  . 102)
 ("/Users/akdeniz/dev/rustlings/exercises/05_vecs/vecs2.rs" . 932)
 ("/Users/akdeniz/dev/rustlings/exercises/05_vecs/vecs1.rs" . 265)
 ("/Users/akdeniz/dev/rustlings/solutions/06_move_semantics/move_semantics4.rs"
  . 123)
 ("/Users/akdeniz/dev/rustlings/exercises/05_vecs/README.md" . 532)
 ("/Users/akdeniz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/event_loop.rs"
  . 14547)
 ("/Users/akdeniz/dev/kairo/.git/"
  (dired-filename . "/Users/akdeniz/dev/kairo/.git/HEAD"))
 ("/Users/akdeniz/dev/federal_test/"
  (dired-filename . "/Users/akdeniz/dev/federal_test/main.js"))
 ("/Users/akdeniz/dev/federal_test/package.json" . 369)
 ("/Users/akdeniz/dev/wukong/main.go" . 165)
 ("/Users/akdeniz/dev/wukong/evaluator/evaluator.go" . 5946)
 ("/Users/akdeniz/dev/logistics-dashboard/components/dashboard/sidebar.tsx"
  . 1252)
 ("/Users/akdeniz/dev/logistics-dashboard/components/dashboard/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/components/dashboard/sidebar.tsx"))
 ("/Users/akdeniz/dev/logistics-dashboard/components/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/components/dashboard"))
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/analytics/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/app/dashboard/analytics/loading.tsx"))
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/live-map/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/app/dashboard/live-map/page.tsx"))
 ("/Users/akdeniz/dev/logistics-dashboard/"
  (dired-filename . "/Users/akdeniz/dev/logistics-dashboard/app"))
 ("/Users/akdeniz/dev/logistics-dashboard/app/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/app/dashboard"))
 ("/Users/akdeniz/dev/logistics-dashboard/components/dashboard/header.tsx"
  . 4376)
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/layout.tsx"
  . 606)
 ("/Users/akdeniz/dev/logistics-dashboard/app/dashboard/analytics/page.tsx"
  . 625)
 ("/Users/akdeniz/dev/logistics-dashboard/components/dashboard/analytics-dashboard.tsx"
  . 2012)
 ("/Users/akdeniz/dev/logistics-dashboard/app/layout.tsx" . 469)
 ("/Users/akdeniz/dev/excel_functions/main.py" . 4314)
 ("/Users/akdeniz/dev/"
  (dired-filename . "/Users/akdeniz/dev/excel_functions"))
 ("/Users/akdeniz/dev/excel_functions/requirements.txt" . 12)
 ("/Users/akdeniz/dev/excel_functions/"
  (dired-filename . "/Users/akdeniz/dev/excel_functions/.github"))
 ("/Users/akdeniz/dev/excel_functions/.github/"
  (dired-filename
   . "/Users/akdeniz/dev/excel_functions/.github/workflows"))
 ("/Users/akdeniz/dev/excel_functions/.github/workflows/"
  (dired-filename
   . "/Users/akdeniz/dev/excel_functions/.github/workflows/build.yml"))
 ("/Users/akdeniz/dev/excel_functions/.github/workflows/build.yml"
  . 602)
 ("/Users/akdeniz/dev/excel_functions/.venv/lib/python3.13/site-packages/PyQt6/QtWidgets.pyi"
  . 65169)
 ("/Users/akdeniz/dev/logistics-dashboard/lib/"
  (dired-filename
   . "/Users/akdeniz/dev/logistics-dashboard/lib/utils.ts"))
 ("/Users/akdeniz/dev/logistics-dashboard/lib/utils.ts" . 46)
 ("/Users/akdeniz/dev/store-app/server/trpc/index.ts" . 248)
 ("/Users/akdeniz/dev/store-app/server/trpc/routers/products.ts" . 330)
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/map/page.tsx" . 2100)
 ("/Users/akdeniz/dev/store-app/"
  (dired-filename . "/Users/akdeniz/dev/store-app/lib"))
 ("/Users/akdeniz/dev/store-app/app/api/trpc/[trpc]/route.ts" . 269)
 ("/Users/akdeniz/dev/tmux-lazygit/scripts/toggle-window.sh" . 438)
 ("/Users/akdeniz/.emacs.d/modules/core.el" . 1870)
 ("/opt/homebrew/Cellar/emacs-plus@31/31.0.50/share/emacs/31.0.50/etc/COPYING"
  . 30809)
 ("/Users/akdeniz/.emacs.d/modules/org.el" . 999)
 ("/Users/akdeniz/.emacs.d/straight/build/"
  (dired-filename
   . "/Users/akdeniz/.emacs.d/straight/build/ace-window"))
 ("/Users/akdeniz/.emacs.d/straight/repos/"
  (dired-filename
   . "/Users/akdeniz/.emacs.d/straight/repos/ace-window"))
 ("/Users/akdeniz/.emacs.d/dirvish/"
  (dired-filename . "/Users/akdeniz/.emacs.d/dirvish/thumbnails"))
 ("/Users/akdeniz/.emacs.d/backups/" . 5223)
 ("/Users/akdeniz/.config/"
  (dired-filename . "/Users/akdeniz/.config/yabai"))
 ("/Users/akdeniz/.config/yabai/"
  (dired-filename . "/Users/akdeniz/.config/yabai/yabairc"))
 ("/Users/akdeniz/dev/dot-config/yabai/yabairc" . 91)
 ("/Users/akdeniz/dev/store-app/app/cart/page.tsx" . 606)
 ("/Users/akdeniz/dev/store-app/node_modules/.pnpm/next@15.2.4_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/dist/client/components/navigation.d.ts"
  . 2227)
 ("/Users/akdeniz/dev/roll-your-own-auth/"
  (dired-filename . "/Users/akdeniz/dev/roll-your-own-auth/src"))
 ("/Users/akdeniz/dev/roll-your-own-auth/src/"
  (dired-filename . "/Users/akdeniz/dev/roll-your-own-auth/src/app"))
 ("/Users/akdeniz/dev/roll-your-own-auth/src/app/login/"
  (dired-filename
   . "/Users/akdeniz/dev/roll-your-own-auth/src/app/login/LoginForm.tsx"))
 ("/Users/akdeniz/dev/roll-your-own-auth/src/app/lib/"
  (dired-filename
   . "/Users/akdeniz/dev/roll-your-own-auth/src/app/lib/session.ts"))
 ("/Users/akdeniz/dev/roll-your-own-auth/src/app/lib/session.ts" . 960)
 ("/Users/akdeniz/dev/roll-your-own-auth/src/app/"
  (dired-filename
   . "/Users/akdeniz/dev/roll-your-own-auth/src/app/lib"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/analytics/page.tsx"
  . 4058)
 ("/Users/akdeniz/dev/store-app/lib/trpc/client.ts" . 327)
 ("/Users/akdeniz/dev/store-app/app/api/trpc/[trpc]/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/api/trpc/[trpc]/route.ts"))
 ("/Users/akdeniz/dev/store-app/app/api/trpc/"
  (dired-filename . "/Users/akdeniz/dev/store-app/app/api/trpc/[trpc]"))
 ("/Users/akdeniz/dev/store-app/app/api/"
  (dired-filename . "/Users/akdeniz/dev/store-app/app/api/trpc"))
 ("/Users/akdeniz/dev/store-app/app/"
  (dired-filename . "/Users/akdeniz/dev/store-app/app/cart"))
 ("/Users/akdeniz/dev/store-app/lib/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/lib/analytics-data.ts"))
 ("/Users/akdeniz/dev/store-app/lib/analytics-data.ts" . 4678)
 ("/Users/akdeniz/dev/store-app/app/scan-store/page.tsx" . 1264)
 ("/Users/akdeniz/dev/wukong/ast/ast.go" . 294)
 ("/Users/akdeniz/.emacs.d/modules/themes/"
  (dired-filename . "/Users/akdeniz/.emacs.d/modules"))
 ("/Users/akdeniz/dev/store-app/public/"
  (dired-filename . "/Users/akdeniz/dev/store-app/public/images"))
 ("/Users/akdeniz/dev/store-app/lib/trpc/"
  (dired-filename . "/Users/akdeniz/dev/store-app/lib/trpc/client.ts"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/product/page.tsx"
  . 1662)
 ("/Users/akdeniz/dev/store-app/node_modules/.pnpm/@trpc+react-query@11.1.0_@tanstack+react-query@5.74.3_react@19.1.0__@trpc+client@11.1.0_bf318fe2845762aca766f2d4ad5f5db6/node_modules/@trpc/react-query/src/createTRPCReact.tsx"
  . 2415)
 ("/Users/akdeniz/work/"
  (dired-filename . "/Users/akdeniz/work/.DS_Store"))
 ("/Users/akdeniz/dev/lyvia/src/app/(auth)/register/page.tsx" . 1774)
 ("/Users/akdeniz/dev/store-app/app/cart/"
  (dired-filename . "/Users/akdeniz/dev/store-app/app/cart/page.tsx"))
 ("/Users/akdeniz/dev/store-app/hooks/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/hooks/use-mobile.tsx"))
 ("/Users/akdeniz/dev/store-app/components/"
  (dired-filename . "/Users/akdeniz/dev/store-app/components/ui"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/"
  (dired-filename . "/Users/akdeniz/dev/store-app/app/(admin)/admin"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/(admin)/admin/page.tsx"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/page.tsx" . 295)
 ("/Users/akdeniz/dev/benihime/src/buffer.zig" . 280)
 ("/Users/akdeniz/dev/Script-Master/cmd/root.go" . 688)
 ("/Users/akdeniz/dev/Script-Master/config/config.go" . 105)
 ("/Users/akdeniz/dev/arcane-royale/src/Player.js" . 1728)
 ("/Users/akdeniz/german/"
  (dired-filename
   . "/Users/akdeniz/german/Akademie Zusatzmaterial.pdf"))
 ("/Users/akdeniz/Library/"
  (dired-filename . "/Users/akdeniz/Library/Mobile Documents"))
 ("/Users/akdeniz/Library/Mobile Documents/"
  (dired-filename
   . "/Users/akdeniz/Library/Mobile Documents/com~apple~CloudDocs"))
 ("/Users/akdeniz/Library/Mobile Documents/com~apple~CloudDocs/"
  (dired-filename
   . "/Users/akdeniz/Library/Mobile Documents/com~apple~CloudDocs/Kitaplar"))
 ("/Users/akdeniz/Library/Mobile Documents/com~apple~CloudDocs/Kitaplar/"
  (dired-filename
   . "/Users/akdeniz/Library/Mobile Documents/com~apple~CloudDocs/Kitaplar/german"))
 ("/Users/akdeniz/Library/Mobile Documents/com~apple~CloudDocs/Kitaplar/german/"
  (dired-filename
   . "/Users/akdeniz/Library/Mobile Documents/com~apple~CloudDocs/Kitaplar/german/Akademie Zusatzmaterial.pdf"))
 ("/Users/akdeniz/dev/store-app/app/map/page.tsx" . 2842)
 ("/Users/akdeniz/dev/store-app/components/store-map.tsx" . 355)
 ("/Users/akdeniz/dev/store-app/app/layout.tsx" . 303)
 ("/Users/akdeniz/dev/store-app/app/(admin)/layout.tsx" . 92)
 ("/Users/akdeniz/dev/store-app/components/admin/map-editor.tsx" . 16)
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/map/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/(admin)/admin/map/page.tsx"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/analytics/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/(admin)/admin/analytics/page.tsx"))
 ("/Users/akdeniz/dev/store-app/components/admin/heatmap.tsx" . 327)
 ("/Users/akdeniz/dev/store-app/components/admin/sidebar.tsx" . 404)
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/product/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/(admin)/admin/product/create"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/product/create/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/(admin)/admin/product/create/page.tsx"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/product/create/page.tsx"
  . 133)
 ("/Users/akdeniz/dev/store-app/components/admin/product-form.tsx"
  . 2593)
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/settings/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/(admin)/admin/settings/page.tsx"))
 ("/Users/akdeniz/dev/store-app/app/(admin)/admin/settings/page.tsx"
  . 185)
 ("/Users/akdeniz/dev/store-app/components/admin/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/components/admin/analytics-dashboard.tsx"))
 ("/Users/akdeniz/dev/store-app/components/admin/analytics-dashboard.tsx"
  . 221)
 ("/Users/akdeniz/dev/store-app/components/ui/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/components/ui/accordion.tsx"))
 ("/Users/akdeniz/dev/store-app/components/ui/table.tsx" . 73)
 ("/Users/akdeniz/dev/store-app/components/ui/chart.tsx" . 80)
 ("/Users/akdeniz/dev/store-app/components/cart-provider.tsx" . 1934)
 ("/Users/akdeniz/dev/store-app/components/cart-map-item.tsx" . 239)
 ("/Users/akdeniz/dev/store-app/app/map/"
  (dired-filename . "/Users/akdeniz/dev/store-app/app/map/page.tsx"))
 ("/Users/akdeniz/dev/store-app/components/snackbar-provider.tsx"
  . 317)
 ("/Users/akdeniz/dev/store-app/app/scan/"
  (dired-filename . "/Users/akdeniz/dev/store-app/app/scan/page.tsx"))
 ("/Users/akdeniz/dev/store-app/app/scan-store/"
  (dired-filename
   . "/Users/akdeniz/dev/store-app/app/scan-store/page.tsx"))
 ("/Users/akdeniz/dev/store-app/node_modules/.pnpm/next@15.2.4_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/dist/client/link.d.ts"
  . 4433)
 ("/Users/akdeniz/dev/arcane-royale/src/VoxelWorld.js" . 1825)
 ("/Users/akdeniz/dev/pokemon-dimensions/"
  (dired-filename . "/Users/akdeniz/dev/pokemon-dimensions/.git"))
 ("/Users/akdeniz/dev/pokemon-dimensions/src/App.ts" . 113)
 ("/Users/akdeniz/dev/lyvia/src/components/ui/form.tsx" . 710)
 ("/Users/akdeniz/dev/store-app/node_modules/.pnpm/lucide-react@0.454.0_react@19.1.0/node_modules/lucide-react/dist/lucide-react.d.ts"
  . 1809540)
 ("/Users/akdeniz/dev/store-app/node_modules/.pnpm/@types+react@19.1.1/node_modules/@types/react/index.d.ts"
  . 156979)
 ("/Users/akdeniz/dev/store-app/components/cart-fab.tsx" . 1674)
 ("/Users/akdeniz/dev/Script-Master/cmd/config.go" . 688)
 ("/Users/akdeniz/.emacs.d/modules/windows.el" . 131)
 ("/Users/akdeniz/dev/lyvia/README.md" . 758)
 ("/Users/akdeniz/dev/lyvia/"
  (dired-filename . "/Users/akdeniz/dev/lyvia/next.config.ts"))
 ("/Users/akdeniz/dev/lyvia/next.config.ts" . 106)
 ("/Users/akdeniz/dev/lyvia/src/"
  (dired-filename . "/Users/akdeniz/dev/lyvia/src/components"))
 ("/Users/akdeniz/dev/lyvia/src/components/"
  (dired-filename
   . "/Users/akdeniz/dev/lyvia/src/components/nav-main.tsx"))
 ("/Users/akdeniz/.config/nvim/"
  (dired-filename . "/Users/akdeniz/.config/nvim/lua"))
 ("/Users/akdeniz/.config/nvim/lua/"
  (dired-filename . "/Users/akdeniz/.config/nvim/lua/plugins"))
 ("/Users/akdeniz/.config/nvim/lua/plugins/"
  (dired-filename
   . "/Users/akdeniz/.config/nvim/lua/plugins/lspconfig.lua"))
 ("/Users/akdeniz/dev/dot-config/nvim/lua/plugins/lspconfig.lua"
  . 1285)
 ("/Users/akdeniz/.emacs.d/places.eld" . 590))
